### ISSUE TITLE
error on line 23

### ISSUE THREAD

**Issue by mhkarimi1383** [javadimoghadam/ddos#2]
Traceback (most recent call last):
  File "ddos.py", line 23, in <module>
    sock.sendto(bytes, (ip, port))
TypeError: an integer is required (got type str)

**Comment by javadimoghadam** [comment]
dear **_@mhkarimi1383_** ,I'm sorry I'm late.
 This error occurs when you enter the combination  ( ctrl + c )  keys. At this point, the separation separates and the loop process fails or breaks. My suggestion to prevent this from happening is to use the ( Ctrl + Z ) keys to exit.
